ajyal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import forms as user_forms, views

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',include('users.urls')),
    path('quiz/',include('quiz.urls')),
    path('course/',include('course.urls')),
    path('notifications/',include('notifications.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='login.html',authentication_form=user_forms.UserLoginForm),name='user-login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='user-logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',form_class=user_forms.UserSetPasswordForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('store_reading_time/<int:pk>/',views.store_reading_time,name='time_reading'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('student/', include(([
    path('',views.StudentQuizListView.as_view(),name='quiz_list'),
    path('take-quiz/<int:pk>',views.take_quiz,name='take_quiz'),
    path('taken/', views.TakenQuizListView.as_view(), name='taken_quiz_list'),
   ],'quiz'),namespace='student')),

    path('teacher/', include(([
    path('',views.QuizListView.as_view(),name='quiz_change_list'),
    path('add/', views.QuizCreateView.as_view(), name='quiz_add'),
    path('<int:pk>/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),
    path('<int:pk>/results/', views.QuizResultsView.as_view(), name='quiz_results'),
    path('<int:pk>/question/add/', views.question_add, name='question_add'),
    path('<int:quiz_pk>/question/<int:question_pk>/', views.question_change, name='question_change'),
    path('<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete'),
   ],'quiz'),namespace='teacher')),
]

htmx_urlpatterns =[
    path('search-quiz/',views.search_quiz,name='search-quiz'),
]

urlpatterns += htmx_urlpatterns

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('<str:username>/profile',views.profile,name='user_profile'),
    path('students/',views.StudentListView.as_view(),name='student_list'),
    path('edit/profile/',views.edit_profile,name='edit_profile'),
    path('contact/',views.contact,name='contact_us')
    
]

htmx_urlpatterns =[
    path('search-student/',views.search_student,name='search-student'),
]

urlpatterns += htmx_urlpatterns

course/models.py
from django.db import models

from django.utils import timezone
# Create your models here.

def user_directory_path(instance, filename):
	
	return f'{instance.prof.username}_courses/{filename}'


class Filliere(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name

class Module(models.Model):
    name = models.CharField(max_length=100)
    filliere = models.ManyToManyField(Filliere, related_name='modules')

    def __str__(self) -> str:
        return self.name

class Course(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(default='default_course_img.jpeg')
    file = models.FileField(upload_to=user_directory_path)
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name='courses')
    prof = models.ForeignKey('users.User',on_delete=models.CASCADE,related_name='courses')
    posted = models.DateTimeField(auto_now_add=timezone.now)

    def __str__(self) -> str:
         return self.title
    class Meta:
        ordering = ('-posted',)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UsernameField,SetPasswordForm
from .models import Student,Prof, User,Contact

class UserLoginForm(AuthenticationForm):
    username = UsernameField(label='Email or Username',
                                widget=forms.TextInput(
                                    attrs = {
                                       'placeholder': 'email or username',
                                       'class': 'form-control'
                                       }
                               ))

    password = forms.CharField(label='Password', 
                                widget=forms.PasswordInput(
                                    attrs = {
                                        'placeholder': 'password',
                                        'class': 'form-control'
                                    }
                                ))
    

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='First Name',widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last Name',widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username','first_name','last_name']

class StudentUpdateForm(forms.ModelForm):
    picture = forms.ImageField(label='Picture',
        widget=forms.FileInput(
        attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = Student
        fields = ['picture']

   

class ProfUpdateForm(forms.ModelForm):
    picture = forms.ImageField(label='Picture',
                              widget=forms.FileInput(
                                  attrs = {
                                        'class': 'form-control',
                                    }
                                ))

    class Meta:
        model = Prof
        fields = ['picture']


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New Password',
                                    widget=forms.PasswordInput(
                                        attrs={'class':'form-control'}
                                    ))
    new_password2 = forms.CharField(label='Confirm New Password',
                                    widget=forms.PasswordInput(
                                        attrs={'class':'form-control'}
                                    ))


class ContactForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(
        attrs={'class':'form-control',
               'id':'name',
               'placeholder':'Enter your name...',
               'data-sb-validations':'required'}
               ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class':'form-control',
               'id':'email',
               'placeholder':'Enter your acadimic email...',
               'data-sb-validations':'required'
               }
    ))
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'id':'phone',
            'type':"tel",
            'placeholder':'+212 634-567-890',
            'data-sb-validations':'required'
        }
    ))
    message = forms.CharField(widget=forms.Textarea(
         attrs={'class':'form-control',
               'id':'message',
               'placeholder':'Enter your message here...',
               'data-sb-validations':'required',
                'style':"height: 10rem"
               }
    ))

    class Meta:
        model = Contact
        fields = ('__all__')

users/views.py
import datetime



from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import Student, User,VisitedCourses
from course.models import Module,Course
from django.contrib import messages
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .decorators import teacher_required
from django.db.models import Count,Max
from .forms import UserUpdateForm,ProfUpdateForm,StudentUpdateForm,ContactForm

def index(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            if not request.user.last_login:
               return redirect('user_profile',request.user.username) 
            return redirect('course_list')
        elif request.user.is_teacher:
            if not request.user.last_login:
               return redirect('user_profile',request.user.username) 
            return redirect('student_list')
        else:
            return redirect('admin/')
    return redirect('user-login')

@login_required
def profile(request,username):
    user = get_object_or_404(User,username=username)
    if user.is_student:
        taken_quizzes = user.student.taken_quizzes.select_related('quiz', 'quiz__course').filter(quiz__course__prof=request.user).order_by('-quiz__date_created')
        visited_courses = user.student.visited_courses.filter(course__prof=request.user).select_related('course', 'course__module').order_by('-duration')
        context = {
                'user_p':user,
                'taken_quizzes':taken_quizzes,
                'visited_courses':visited_courses,
                }
        return render(request,'user/student_profile.html',context=context)
    else:
        courses= user.courses.all()
        quizzes = user.quizzes.annotate(questions_count=Count('questions', distinct=True))

        context = {
            'user_p':user,
            'courses':courses,
            'quizzes':quizzes
        }
        return render(request,'user/teacher_profile.html',context=context)

@method_decorator([login_required,teacher_required],name='dispatch')
class StudentListView(ListView):
    model = Student
    context_object_name = 'students'
    template_name = 'user/student_list.html'

    def get_queryset(self):
        teacher_courses = self.request.user.courses.all()
        modules = Module.objects.filter(courses__in=teacher_courses)
        queryset = Student.objects.filter(modules__in=modules).annotate(
            max_quiz_score=Max('taken_quizzes__score'),
            duration=Max('visited_courses__duration')
        ).order_by('max_quiz_score','duration')
        return queryset
    
    

@login_required
def edit_profile(request):
    if request.method == "POST":
        if request.user.is_teacher:
            u_form = UserUpdateForm(request.POST,instance=request.user)
            p_form = ProfUpdateForm(request.POST,request.FILES,instance=request.user.prof)
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request,'your account has been Updated!')
                return redirect('edit_profile')
        else:
            u_form = UserUpdateForm(request.POST,instance=request.user)
            p_form = StudentUpdateForm(request.POST,request.FILES,instance=request.user.student)
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request,'your account has been Updated!')
                return redirect('edit_profile')
    else:
        if request.user.is_teacher:
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfUpdateForm(instance=request.user.prof)
        else:
            u_form = UserUpdateForm(instance=request.user)
            p_form = StudentUpdateForm(instance=request.user.student)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }


    return render(request,'user/edit_profile.html',context)

@login_required
def store_reading_time(request,pk):
    if request.method == 'POST':
        course = get_object_or_404(Course,pk=pk)
        exist = VisitedCourses.objects.filter(course = course).exists()

        visited_course = VisitedCourses.objects.get(course = course) if exist else None
        
        
        start_time = datetime.datetime.fromisoformat(request.POST['start_time'])
        end_time = datetime.datetime.fromisoformat(request.POST['end_time'])
            
        duration_microseconds = end_time - start_time
        days, seconds = duration_microseconds.days, duration_microseconds.seconds
        hours = int(days * 24 + seconds / 3600)
        minutes = int((seconds % 3600) / 60)
        seconds = int(seconds % 60)
        
        formatted_duration = f'{hours} h: {minutes} min: {seconds} sec'

        if not exist:
            visited_course = VisitedCourses.objects.create(
                student=request.user.student,
                course=course,
                start_time=start_time,
                end_time=end_time,
                duration=duration_microseconds,
                formatted_duration=formatted_duration
            )
            return JsonResponse({'success': True})
        
        visited_course.duration = duration_microseconds
        visited_course.formatted_duration = formatted_duration
        visited_course.save()
    return JsonResponse({'success': True})

@login_required
def search_student(request):
    search_text = request.POST.get('search')

    results = Student.objects.filter(user__username__icontains = search_text,courses__prof=request.user).distinct()

    context = {
        'results':results
    }

    return render(request,'user/_search_results.html',context)


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Your Message was sent succesfully. We will respond as soon as we can")
            return redirect('user-login')
    else:
        form = ContactForm()

    return render(request,'contact.html',context={
        'form':form
    })        

users/templates/_sidebar.html
    


  {% load static %}
  {% if user.is_authenticated %}
        {% if user.is_teacher %}
            <nav id="sidebar">
            <div class="sidebar-header">
                <h3><img src="{% static "img/logo.png" %} " class="img-fluid"/><span>Ajyal</span></h3>
            </div>
            <ul class="list-unstyled components">
                <li  class="active">
                        <a href="{% url "student_list" %}" class="dashboard"><i class="material-icons">dashboard</i><span>Your Students</span></a>
                </li>
		
		      <div class="small-screen navbar-display">
                <li class="dropdown d-lg-none d-md-block d-xl-none d-sm-block">
                    <a href="#homeSubmenu0" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
					<i class="material-icons">notifications</i><span> {{notification_count | default:"0"}} notification</span></a>
                    <ul class="collapse list-unstyled menu" id="homeSubmenu0">
                        <!-- notifications -->
                                {% for notification in notifications %}
                                    <li>
                                    <a href="">{{notification.content}}</a>
                                    </li>
                                {% endfor %}
                                    
                    </ul>
                </li>

				 <li  class="d-lg-none d-md-block d-xl-none d-sm-block">
                    <a href="{% url "edit_profile" %}"><i class="material-icons">person</i><span>Profile</span></a>
                </li>		
			</div>
			  
			<li class="">
                   
                    
                  
                    <a href="{% url "notification_create" %}"><i class="material-icons">notifications</i> <span>Create Notification</span></a>
               
                </li>
                <li class="dropdown">
                    <a href="#homeSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
					<i class="material-icons">menu_book</i><span>Courses</span></a>
                    <ul class="collapse list-unstyled menu" id="homeSubmenu1">
                        <li>
                            <a href="{% url "course_list" %}">My Courses</a>
                        </li>
                        <li>
                            <a href="{% url "course_create" %}">Add Course</a>
                        </li>
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
					<i class="material-icons">quiz</i><span>Quizzes</span></a>
                    <ul class="collapse list-unstyled menu" id="pageSubmenu2">
                        <li><a href="{% url "teacher:quiz_change_list" %}">My Quizzes</a></li>
                        <li>
                            <a href="{% url "teacher:quiz_add" %}">Add quiz</a>
                        </li>
                    </ul>
                </li>
				
				 
				
				
               
			   
			   
			   
               
			   
			     
               
               <li class="">
                    <form method="post" action="{% url "user-logout" %}"  style="margin-bottom:0" >
                    
                  {% csrf_token %}
                    <a><button class="btn-as-text"  type="submit"><i class="material-icons">logout</i><span>Log out</span></button></a>
                </form>
                </li>
				
               
               
            </ul>

           
        </nav>
        {% else %}
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3><img src="{% static 'img/logo.png' %} " class="img-fluid"/><span>Ajyal</span></h3>
            </div>

            <ul class="list-unstyled components">
		
		      <div class="small-screen navbar-display">
                <li class="dropdown d-lg-none d-md-block d-xl-none d-sm-block">
                    <a href="#homeSubmenu0" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
					<i class="material-icons">notifications</i><span> {{notification_count | default:"0"}} notification</span></a>
                    <ul class="collapse list-unstyled menu" id="homeSubmenu0">
                                    {% for notification in notifications %}
                                    {% if notification.is_quiz_notif %}
                                        <li hx-post="{% url "change-stat" notification.pk %}">
                                        <a href="{% if notification.quiz_notifications.quiz.pk %} {% url "student:take_quiz" notification.quiz_notifications.quiz.pk %}{% endif %}">{{notification.content}}</a>
                                        </li>
                                    {% else %}
                                    <li hx-post="{% url "change-stat" notification.pk %}">
                                        <a href="{% if notification.course_notifications.course.pk %} {% url "course_detail" notification.course_notifications.course.pk %}{% endif %}">{{notification.content}}</a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                    
                    </ul>
                </li>
				
				
				 <li  class="d-lg-none d-md-block d-xl-none d-sm-block">
                    <a href="{% url "edit_profile" %}"><i class="material-icons">person</i><span>Profile</span></a>
                </li>
				
				</div>
			
			
                <li class="">
                    <a href="{% url "course_list" %}"  >
					<i class="material-icons">menu_book</i><span>Courses</span></a>
                    
                </li>
                
                <li class="dropdown">
                    <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
					<i class="material-icons">quiz</i><span>Quizzes</span></a>
                    <ul class="collapse list-unstyled menu" id="pageSubmenu2">
                        <li>
                            <a href="{% url "student:quiz_list" %}">Quizzes</a>
                        </li>
                        <li>
                            <a href="{% url "student:taken_quiz_list" %}">Taken Quizzes</a>
                        </li>
                    </ul>
                </li>
				
				 
               
               <li class="">
                    <form method="post" action="{% url "user-logout" %}"  style="margin-bottom:0" >
                    
                  {% csrf_token %}
                    <a><button class="btn-as-text"  type="submit"><i class="material-icons">logout</i><span>Log out</span></button></a>
                </form>
                </li>
            </ul>

           
        </nav>
		
		

        {% endif %}
     
    {% endif %}
        

users/templates/_topbar.html
{% load static %}
{% if user.is_authenticated %}
    <div class="top-navbar">
            <nav class="navbar navbar-expand-sm">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="d-xl-block d-lg-block d-md-mone d-none">
                        <span class="material-icons">arrow_back_ios</span>
                    </button>
					
                    <button class="d-inline-block d-lg-none ml-auto more-button" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="material-icons">menu</span>
                    </button>
    {% if user.is_teacher %}
        

                    <div class="collapse navbar-collapse d-lg-block d-xl-block d-sm-none d-md-none d-none" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">   
                            <li class="dropdown nav-item active">
                                <a href="#" class="nav-link" data-toggle="dropdown" >
                                   <span class="material-icons">notifications</span>
								   <span class="notification">{{notification_count | default:"0"}}</span>
                               </a>
                               {% if notification_count > 0 %}
                                <ul class="dropdown-menu">
                                    {% for notification in notifications %}
                                     <form>
                                        {% csrf_token %}
                                    <li hx-post="{% url "change-stat" notification.pk %}">
                                    <a href="{% url "student_list" %}" >{{notification.content}}</a>
                                    </li>
                                     </form>
                                {% endfor %}
                                  
                                </ul>
                                {% endif %}
                            </li>

                            
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "edit_profile" %}">
                                    <img src="{% if user.prof.picture %}{{user.prof.picture.url}}{% endif %} " class="img-fluid rounded-circle me-3" style="width:35px">
								</a>
                            </li>
                        </ul>
                    </div>
               
    {% else %}
    <div class="collapse navbar-collapse d-lg-block d-xl-block d-sm-none d-md-none d-none" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">   
                            <li class="dropdown nav-item active">
                                <a href="#" class="nav-link" data-toggle="dropdown">
                                   <span class="material-icons">notifications</span>
								   <span class="notification">{{notification_count | default:"0"}}</span>
                               </a>
                               <!-- notifications here-->
                                {% if notification_count > 0  %}
                                <ul class="dropdown-menu">
                                    
                                    {% for notification in notifications %}
                                    <form>
                                        {% csrf_token %}
                                    {% if notification.is_quiz_notif %}
                                    
                                        
                                        <li hx-post="{% url "change-stat" notification.pk %}">
                                        <a href="{% if notification.quiz_notifications.quiz.pk %} {% url "student:take_quiz" notification.quiz_notifications.quiz.pk %}{% endif %}" data-quiz-id={{notification.quiz_notifications.quiz.pk}}>{{notification.content}}</a>
                                        </li>
                                    
                                    {% elif notification.is_course_notif %}
                                    
                                    <li hx-post="{% url "change-stat" notification.pk %}">
                                        <a href="{% if notification.course_notifications.course.pk %} {% url "course_detail" notification.course_notifications.course.pk %}{% endif %}">{{notification.content}}</a>
                                    </li>
                                    
                                    {% else %}
                                        <li hx-post="{% url "change-stat" notification.pk %}">
                                        <a href="">{{notification.content}}</a>
                                        </li>
                                    {% endif %}
                                    </form>
                                  
                                    {% endfor %}
    
                                  
                                </ul>
                                {% endif %}
                            </li>

                            
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "edit_profile" %}">
                                    <img src="{% if user.student.picture %}{{user.student.picture.url}}{% endif %} " class="img-fluid rounded-circle me-3" width="35">
								</a>
                            </li>
                        </ul>
                    </div>
    {% endif %}
                </div>
            </nav>
	    </div>
{% endif %}

users/templates/login.html
 {% extends "index.html" %}
 {% load static %}
 {% block title %}
  <title>Login</title>
 {% endblock  %}
 {% block content %}
 
 <section>
  {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                </div>
              {% endfor %}
    <div class="container py-4">
      <div
      class="row gx-5 align-items-center justify-content-center "
    >
    <div class="col col-md-9">
      <h2 style="text-align:center"> Welcome To Ajyal</h2>
    <form method="post">
        {% csrf_token %}
  <!-- Email input -->
  <div class="form-outline mb-4">
    <label class="form-label" for="form2Example1">Email address or username</label>
    {{form.username}}
    
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <label class="form-label" for="form2Example2">Password</label>
    {{form.password}}
    
  </div>

  <div class="form-outline mb-4">
                                        {% if form.non_field_errors %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error }}</strong>
                                            </div>
                                        {% endfor %}
                                        {% endif %}
                                    </div>

  

    <div class="col">
      <!-- Simple link -->
      <a href="{% url "password_reset" %}">Forgot password?</a>
    </div>
    <hr>

    <div class="d-grid">
    <button type="submit" class="btn btn-primary rounded-pill btn-lg">Sign in</button>
  </div>


  

  
  
</form>
</div>
</div>
</div >
</section>
 {% endblock  %}
    

users/templates/logout.html
 {% extends "index.html" %}

{% block content %}

    
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url "user-login" %}">log in again</a>
            </small>
        </div>

{% endblock  %}