ajyal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import forms as user_forms, views

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',include('users.urls')),
    path('quiz/',include('quiz.urls')),
    path('course/',include('course.urls')),
    path('notifications/',include('notifications.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='login.html',authentication_form=user_forms.UserLoginForm),name='user-login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='user-logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',form_class=user_forms.UserSetPasswordForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('store_reading_time/<int:pk>/',views.store_reading_time,name='time_reading'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('student/', include(([
    path('',views.StudentQuizListView.as_view(),name='quiz_list'),
    path('take-quiz/<int:pk>',views.take_quiz,name='take_quiz'),
    path('taken/', views.TakenQuizListView.as_view(), name='taken_quiz_list'),
   ],'quiz'),namespace='student')),

    path('teacher/', include(([
    path('',views.QuizListView.as_view(),name='quiz_change_list'),
    path('add/', views.QuizCreateView.as_view(), name='quiz_add'),
    path('<int:pk>/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),
    path('<int:pk>/results/', views.QuizResultsView.as_view(), name='quiz_results'),
    path('<int:pk>/question/add/', views.question_add, name='question_add'),
    path('<int:quiz_pk>/question/<int:question_pk>/', views.question_change, name='question_change'),
    path('<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete'),
   ],'quiz'),namespace='teacher')),
]

htmx_urlpatterns =[
    path('search-quiz/',views.search_quiz,name='search-quiz'),
]

urlpatterns += htmx_urlpatterns

quiz/models.py
from django.db import models
from django.utils import timezone
from course.models import Course



class Quiz(models.Model):
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizzes')
    date_created = models.DateTimeField(auto_now_add=timezone.now)

    def __str__(self):
        return self.name
    
class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField(null=False)
    date_created = models.DateTimeField(auto_now_add=timezone.now)
    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)
    date_created = models.DateTimeField(auto_now_add=timezone.now)

    def __str__(self) -> str:
        return self.text


class StudentAnswer(models.Model):
    student = models.ForeignKey('users.Student', on_delete=models.CASCADE, related_name='quiz_student_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

quiz/forms.py
from django import forms
from .models import Question,Answer,StudentAnswer
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError(_('Mark at least one answer as correct.'), code='no_correct_answer')

class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

quiz/views.py
from django.forms import inlineformset_factory
from django.shortcuts import redirect, render,get_object_or_404
from django.views.generic import (ListView,CreateView,UpdateView,DeleteView,DetailView)
from django.utils.decorators import method_decorator
from course.models import Course
from users.decorators import student_required,teacher_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from django.db import transaction
from django.db.models import Count,Avg
from django.urls import reverse, reverse_lazy

from .models import Answer, Question, Quiz
from .forms import BaseAnswerInlineFormSet, QuestionForm, TakeQuizForm
from users.models import TakenQuiz


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('-date_created', )
    context_object_name = 'quizzes'
    template_name = 'quiz/prof/quiz_change_list.html'
    paginate_by = 10
    
    def get_queryset(self):
        queryset = self.request.user.quizzes \
            .select_related('course') \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_quizzes', distinct=True)).order_by('-date_created')
        return queryset


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizCreateView(CreateView):
    model = Quiz
    fields = ('name', 'course', )
    template_name = 'quiz/prof/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.owner = self.request.user
        quiz.save()
        messages.success(self.request, 'The quiz was created with success! Go ahead and add some questions now.')
        return redirect('teacher:quiz_change', quiz.pk)

@method_decorator([login_required, teacher_required], name='dispatch')
class QuizUpdateView(UserPassesTestMixin,UpdateView):
    model = Quiz
    fields = ('name', 'course', )
    context_object_name = 'quiz'
    template_name = 'quiz/prof/quiz_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.quizzes.all()
    
    def test_func(self) -> bool | None:
        quiz = self.get_object()
        if self.request.user == quiz.owner:
            return True
        return False

    def get_success_url(self):
        return reverse('teacher:quiz_change', kwargs={'pk': self.object.pk})

@method_decorator([login_required, teacher_required], name='dispatch')
class QuizDeleteView(UserPassesTestMixin,DeleteView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'quiz/prof/quiz_delete_confirm.html'
    success_url = reverse_lazy('teacher:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()
    
    def test_func(self) -> bool | None:
        quiz = self.get_object()
        if self.request.user == quiz.owner:
            return True
        return False


@method_decorator([login_required, teacher_required], name='dispatch')
class QuizResultsView(UserPassesTestMixin,DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'quiz/prof/quiz_results.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        quiz = self.get_object()
        taken_quizzes = quiz.taken_quizzes.select_related('student__user').order_by('-date')
        total_taken_quizzes = taken_quizzes.count()
        quiz_score = quiz.taken_quizzes.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_quizzes': taken_quizzes,
            'total_taken_quizzes': total_taken_quizzes,
            'quiz_score': quiz_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all().order_by('-date_created')
    
    def test_func(self) -> bool | None:
        quiz = self.get_object()
        if self.request.user == quiz.owner:
            return True
        return False

@login_required
@teacher_required
def question_add(request, pk):
    # By filtering the quiz by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # quiz will be able to add questions to it.
    quiz = get_object_or_404(Quiz, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('teacher:question_change', quiz.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'quiz/prof/question_add_form.html', {'quiz': quiz, 'form': form})


@login_required
@teacher_required
def question_change(request, quiz_pk, question_pk):
    quiz = get_object_or_404(Quiz, pk=quiz_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, quiz=quiz)

    AnswerFormSet = inlineformset_factory(
        Question,  
        Answer,
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('teacher:quiz_change', quiz.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'quiz/prof/question_change_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'formset': formset
    })


@method_decorator([login_required, teacher_required], name='dispatch')
class QuestionDeleteView(UserPassesTestMixin,DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'quiz/prof/question_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['quiz'] = question.quiz
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(request, 'The question %s was deleted with success!' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(quiz__owner=self.request.user)
    
    def test_func(self) -> bool | None:
        question = self.get_object()
        if self.request.user == question.quiz.owner:
            return True
        return False

    def get_success_url(self):
        question = self.get_object()
        return reverse('teacher:quiz_change', kwargs={'pk': question.quiz_id})


@method_decorator([login_required, student_required], name='dispatch')
class StudentQuizListView(ListView):
    model = Quiz
    ordering = ('-date_created', )
    context_object_name = 'quizzes'
    template_name = 'quiz/student/quiz_list.html'
    paginate_by = 10
    def get_queryset(self):
        student = self.request.user.student
        student_modules = student.modules.all()
        student_courses = Course.objects.filter(module__in=student_modules)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(course__in=student_courses) \
            .exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset
    
@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'quiz/student/taken_quiz_list.html'
    paginate_by = 10
    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__course') \
            .order_by('quiz__date_created')
        return queryset

@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'quiz/student/taken_quiz_list.html')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    try:
        progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    except ZeroDivisionError:
        messages.error(request,"This Quiz Has no Question yet")
        return redirect('student:quiz_list')
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)

quiz/templates/quiz/prof/question_add_form.html
{% extends "_base.html" %} {% block title %}<title>Add Question</title>{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="card" style="min-height: 485px">
      <div class="card-header card-header-text">
        <h2 class="mb-3">Add a new question</h2>
        <p class="lead">
          Add first the text of the question. In the next step you will be able
          to add the possible answers.
        </p>
      </div>

        <div class="col-md-7 col-sm-8 col-12">
                <form method="post" novalidate>
                {% csrf_token %} {{ form|crispy }}
                <div>
                  <button type="submit" class="btn btn-success">Save</button>
                  <a
                      href="{% url 'teacher:quiz_change' quiz.pk %}"
                      class="btn btn-outline-secondary"
                      role="button"
                      >Nevermind</a
                  >
              </div>
                </form>
        </div>
    </div>
  </div>
</div>
</div>
  {% endblock content %}

quiz/templates/quiz/prof/question_change_form.html
{% extends '_base.html' %} {% block content %}
{% load crispy_forms_tags crispy_forms_filters %}
<div class="row">
  <div class="col-lg-15 col-md-12">
    <div class="card" style="min-height: 485px">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'teacher:quiz_change_list' %}">My Quizzes</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'teacher:quiz_change' quiz.pk %}"
              >{{ quiz.name }}</a
            >
          </li>
          <li class="breadcrumb-item active" aria-current="page">
            {{ question.text }}
          </li>
        </ol>
      </nav>
      <h2 class="mb-3">{{ question.txt }}</h2>
      <form method="post" novalidate>
        {% csrf_token %} {{ formset.management_form }} {{ form|crispy }}
        <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
          <div class="card-header">
            <div class="row">
              <div class="col-8">
                <strong>Answers</strong>
              </div>
              <div class="col-2">
                <strong>Correct?</strong>
              </div>
              <div class="col-2">
                <strong>Delete?</strong>
              </div>
            </div>
          </div>
          {% for error in formset.non_form_errors %}
          <div class="card-body bg-danger border-danger text-white py-2">
            {{ error }}
          </div>
          {% endfor %}
          <div class="list-group list-group-flush list-group-formset">
            {% for form in formset %}
            <div class="list-group-item">
              <div class="row">
                <div class="col-8">
                  {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                  {{ form.text|as_crispy_field }} {% if form.instance.pk and form.text.value != form.instance.text %}
                  <p class="mb-0 mt-1">
                    <small class="text-muted font-italic"
                      ><strong>Old answer:</strong> {{ form.instance.text }}</small
                    >
                  </p>
                  {% endif %}
                </div>
                <div class="col-2">{{ form.is_correct }}</div>
                <div class="col-2">
                  {% if form.instance.pk %} {{ form.DELETE }} {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        
        <button type="submit" class="btn btn-success">Save changes</button>
        <a
          href="{% url 'teacher:quiz_change' quiz.pk %}"
          class="btn btn-outline-secondary"
          role="button"
          >Nevermind</a
        >
        <a
          href="{% url 'teacher:question_delete' quiz.pk question.pk %}"
          class="btn btn-danger float-right"
          >Delete</a
        >
      </form>
    </div>
  </div>
  </div>
{% endblock %}

quiz/templates/quiz/prof/question_delete_confirm.html
{% extends '_base.html' %} {% block title %}<title>Confirm Quiz deletion</title
>{% endblock title %} {% block content %}
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="card" style="min-height: 485px">
      <div class="card-header card-header-text">
        <h2 class="mb-3">Confirm deletion</h2>
        <p class="lead">
          Are you sure you want to delete the question
          <strong>"{{ question.text }}"</strong>? There is no going back.
        </p>
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        <form method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger btn-lg">
            Yes, I'm sure
          </button>
          <a
            href="{% url 'teacher:question_change' quiz.pk question.pk %}"
            class="btn btn-outline-secondary btn-lg"
            role="button"
            >Nevermind</a
          >
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

quiz/templates/quiz/prof/quiz_add_form.html
{% extends "_base.html" %}
{% block title %}<title>Quizzes</title>{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
 <div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card" style="min-height: 485px">
            <div class="card-header card-header-text">
                <h2 class="mb-3">Add a new quiz</h2>
            </div>
 
            <div class="col-md-6 col-sm-8 col-12">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Save</button>
                        <a href="{% url 'teacher:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

quiz/templates/quiz/prof/quiz_change_form.html
{% extends '_base.html' %}

{% block title %}<title>Complete adding your quiz</title>{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'teacher:quiz_results' quiz.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'teacher:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a href="{% url 'teacher:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'teacher:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'teacher:question_add' quiz.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'teacher:question_add' quiz.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
</div>
{% endblock %}

quiz/templates/quiz/prof/quiz_change_list.html
{% extends "_base.html" %} 
{% block title %}<title>Quizzes</title>{% endblock title %}
{% block content %}
{% include "quiz/_search_quiz.html" %}
<div class="row">
    <div class="col-lg-15 col-md-12">
        <div class="card" style="min-height: 485px">
            <div class="card-header card-header-text">
                <h4 class="card-title">Quizzes</h4>
            </div>
        
        <div class="card-content table-responsive">
            <table class="table table-hover">
                <thead class="text-primary">
                    <tr>
                        <th>Quiz</th>
                        <th>Course</th>
                        <th>Questions</th>
                        <th>Taken</th>
                        <th></th>
                                
                    </tr>
                </thead>
                <tbody>
                    {% for quiz in quizzes %}
                        <tr>
                            <td><a href="{% url 'teacher:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
                            <td>{{ quiz.course.title }}</td>
                            <td>{{ quiz.questions_count }}</td>
                            <td>{{ quiz.taken_count }}</td>
                            <td class="text-right">
                                <a href="{% url "teacher:quiz_results" quiz.pk %}" class="btn btn-primary">View results</a>
                            </td>
                        </tr>
                                            
                    {% empty %}
                        <tr>
                            <td class="bg-light text-center font-italic" colspan="5">You haven't created any quiz yet.</td>
                        </tr>
                    {% endfor %}             
                    </tbody>
                </table>
            </div>
               
        </div>
    </div>
</div>

{% if is_paginated %}
   {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
   {% endif %}
   {% for num in page_obj.paginator.page_range %}
        {% if num == page_obj.page_number %}
            <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
        {% elif num > page_obj.page_number|add:'-3' and num < page_obj.page_number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
        {% endif %}
   {% endfor %}

   {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next page</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last Page</a>
   {% endif %}


   {% endif %}
{% endblock content %}

quiz/templates/quiz/prof/quiz_delete_confirm.html
{% extends '_base.html' %}



{% block content %}
  <div class="row">
  <div class="col-lg-7 col-md-12">
    <div class="card" style="min-height: 485px">
      <div class="card-header card-header-text">
        <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the quiz <strong>"{{ quiz.name }}"</strong>? There is no going back.</p>
      </div>
  
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teacher:quiz_change' quiz.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
</div>
</div>
</div>
</div>
{% endblock %}

quiz/templates/quiz/prof/quiz_results.html
{% extends '_base.html' %} {% block content %}

<div class="row">
  <div class="col-lg-15 col-md-12">
    <div class="card" style="min-height: 485px">
      <div class="card-header card-header-text">
        <strong>Taken Quizzes</strong>
        <span class="badge badge-pill badge-primary float-right"
          >Average Score: {{ quiz_score.average_score|default_if_none:0.0}}</span
        >
      </div>
      <div class="card-content table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th>Student</th>
              <th>Date</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            {% for taken_quiz in taken_quizzes %}
            <tr>
              <td><a href="{% url "user_profile" taken_quiz.student.user.username %}"><strong>{{ taken_quiz.student.user.username }}</strong></a></td>
              <td>{{ taken_quiz.date|date:'d-M-Y' }}</td>
              <td>{{ taken_quiz.score }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="card-footer text-muted">
        Total respondents: <strong>{{ total_taken_quizzes }}</strong>
      </div>
    </div>
  </div>
</div>

{% if is_paginated %}
   {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
   {% endif %}
   {% for num in page_obj.paginator.page_range %}
        {% if num == page_obj.page_number %}
            <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
        {% elif num > page_obj.page_number|add:'-3' and num < page_obj.page_number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
        {% endif %}
   {% endfor %}

   {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next page</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last Page</a>
   {% endif %}


   {% endif %}
{% endblock %}